plugins {
    id 'fabric-loom' version '1.11-SNAPSHOT'
}

version = '1.0.0'
group = 'phong.pyctl'
base { archivesName = 'pyctl' }

repositories { mavenCentral() }

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    implementation "org.python:jython-standalone:2.7.3"
    include "org.python:jython-standalone:2.7.3"
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
